/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lobby.component;

/**
 *
 * @author QuocBao
 */
public class AvatarPanel extends javax.swing.JPanel {

    /**
     * Creates new form AvatarPanel
     */
    public AvatarPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatarLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(129, 129));
        setMinimumSize(new java.awt.Dimension(129, 129));
        setPreferredSize(new java.awt.Dimension(129, 129));

        avatarLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initAvatar(String avatarUrl) {
        avatarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource(avatarUrl))); // NOI18N
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLbl;
    // End of variables declaration//GEN-END:variables
}
